import { useState } from "react";
import { Link } from "react-router-dom";

// ASSUMPTION: adjust these two import paths to match your actual shared
// header/footer components — I don't have their real location, so this
// points at the conventional spot. If your project keeps them elsewhere
// (e.g. "../components/layout/Header"), just update these two lines.
import Header from "../shared/Header";
import Footer from "../shared/Footer";

/**
 * bookConsultation.jsx
 * Patient-facing booking flow, lives at "/book".
 * Assumes the patient is already signed in and email-verified (per the
 * architecture, accounts are created before booking) — wrap this route in
 * whatever auth guard / protected route pattern the rest of the app uses.
 *
 * Uses Header with variant="minimal" (logo + a "Cancel" link back to "/"),
 * not the full site header — this is a focused task flow, and the full
 * header's nav/sign-in/book items would just be noise here. This also
 * matters functionally: the "full" header is `position: fixed` and needs
 * a page to add top padding to clear it (see Home.jsx). The "minimal"
 * header is `sticky` instead, so it takes its own space in the layout and
 * needs no such padding — using it here is what fixes the header
 * previously overlapping the top of this page.
 *
 * Backend integration points are marked MOCK below. Swap createBookingDraft
 * and submitPaymentProof for real calls to your Cloud Functions, e.g.:
 *   import { getFunctions, httpsCallable } from "firebase/functions";
 *   const createBookingDraft = httpsCallable(getFunctions(), "createBookingDraft");
 *
 * Placeholder values to update before shipping:
 * - CONSULTATION_FEES amounts
 * - MOMO_NUMBER / MOMO_NAME
 *
 * Defaults: General OPD + Online are pre-selected on step 0, since that's
 * the most common path through this flow. Patients can still switch to
 * Surgical and/or In person before continuing.
 *
 * Payment reference vs. transaction ID — these are two different codes:
 * - referenceCode: generated by US (booking.referenceCode). We tell the
 *   patient to put it in the MoMo transfer note, so our team can match an
 *   incoming transfer to this specific booking.
 * - momoTransactionId: generated by the MOBILE NETWORK, not by us. It
 *   arrives in the SMS the patient receives after sending the money. We
 *   ask them to copy it from that SMS in step 2, as a second, independent
 *   way to verify the same payment.
 * The amount field in step 2 is prepopulated with the expected fee (set
 * as soon as the booking draft is created) but stays editable, in case
 * the patient actually sent a different amount.
 *
 * Back navigation: steps 1 and 2 show a "Back" arrow to the previous step.
 * It only changes which step is showing — form values already entered
 * (dates, phone, MoMo name, transaction ID, amount) stay in state, so
 * going back and forward again doesn't lose anything the patient typed.
 * Step 0 has nothing to go back to (the header's Cancel link covers
 * leaving the flow entirely), and step 3 is a completed state, not
 * something to undo.
 */

const CONSULTATION_FEES = {
  OPD: 50,
  SURGICAL: 100,
};

const MOMO_NUMBER = "024 000 0000";
const MOMO_NAME = "Holy Family Catholic Hospital";

const STEP_LABELS = ["Consultation", "Payment", "Confirm payment", "Done"];

// ---- MOCK backend calls, replace with real Cloud Function calls ----
function createBookingDraft({ type, mode, dateOfBirth, sex, location, phone }) {
  return new Promise((resolve) => {
    setTimeout(() => {
      const code =
        "HFH-" + Math.random().toString(36).slice(2, 8).toUpperCase();
      resolve({ bookingId: "draft_" + Date.now(), referenceCode: code });
    }, 700);
  });
}

function submitPaymentProof({
  bookingId,
  momoName,
  momoReference,
  momoTransactionId,
  amountPaid,
}) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (!momoReference.trim()) {
        reject(
          new Error("Missing reference code — please go back and try again."),
        );
        return;
      }
      if (!momoTransactionId.trim()) {
        reject(
          new Error(
            "Enter the Transaction ID from your mobile money confirmation SMS.",
          ),
        );
        return;
      }
      resolve({ status: "pending_review" });
    }, 700);
  });
}
// ---------------------------------------------------------------------

// Small inline copy-to-clipboard button. Falls back silently if the
// clipboard API isn't available (e.g. non-HTTPS preview environments).
function CopyButton({ value }) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // Clipboard API unavailable — no-op, user can still select/copy manually.
    }
  }

  return (
    <button
      type="button"
      onClick={handleCopy}
      aria-label={copied ? "Copied" : "Copy reference code"}
      className="inline-flex items-center gap-1 rounded-full border border-[#14213833] px-2.5 py-1 text-[13px] font-medium text-[#142138e6]
                 hover:border-[var(--ink)] hover:text-[var(--ink)] transition shrink-0"
    >
      {copied ? (
        <>
          <svg width="12" height="12" viewBox="0 0 20 20" fill="none">
            <path
              d="M4 10l4 4l8-8"
              stroke="currentColor"
              strokeWidth="2.4"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
          Copied
        </>
      ) : (
        <>
          <svg width="12" height="12" viewBox="0 0 20 20" fill="none">
            <rect
              x="7"
              y="7"
              width="10"
              height="10"
              rx="1.5"
              stroke="currentColor"
              strokeWidth="1.6"
            />
            <path
              d="M4 13V4.5A1.5 1.5 0 0 1 5.5 3H13"
              stroke="currentColor"
              strokeWidth="1.6"
              strokeLinecap="round"
            />
          </svg>
          Copy
        </>
      )}
    </button>
  );
}

// Back arrow used between steps. Only steps 1 and 2 render this — see the
// note in the file docblock on why 0 and 3 don't.
function BackButton({ onClick, children = "Back" }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="inline-flex items-center gap-1.5 mb-6 text-[15px] font-medium text-[#142138b8]
                 hover:text-[var(--ink)] transition-colors
                 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--ink)] rounded"
    >
      <svg
        width="16"
        height="16"
        viewBox="0 0 20 20"
        fill="none"
        aria-hidden="true"
      >
        <path
          d="M12.5 5L7 10l5.5 5"
          stroke="currentColor"
          strokeWidth="1.8"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
      {children}
    </button>
  );
}

export default function BookConsultation() {
  // MOCK — booking is currently designed as a signed-in flow.
  // Replace this with the real auth state when authentication is wired up.
  const [isLoggedIn] = useState(true);
  const [step, setStep] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  // Pre-selected: General OPD + Online, the most common path. Patients can
  // still change either before continuing.
  const [type, setType] = useState("OPD"); // "OPD" | "SURGICAL"
  const [mode, setMode] = useState("online"); // "online" | "offline"
  const [dateOfBirth, setDateOfBirth] = useState("");
  const [sex, setSex] = useState("");
  const [location, setLocation] = useState("");
  // Patient details collected during booking.
  // Current fields: date of birth, sex, location, and phone number.
  const [phone, setPhone] = useState("");

  const [booking, setBooking] = useState(null); // { bookingId, referenceCode }

  const [momoName, setMomoName] = useState("");
  const [momoTransactionId, setMomoTransactionId] = useState("");
  const [amountPaid, setAmountPaid] = useState("");

  const fee = type ? CONSULTATION_FEES[type] : null;

  function goToStep(n) {
    setError("");
    setStep(n);
  }

  async function handleContinueFromDetails() {
    if (!type || !mode) {
      setError("Choose a consultation type and a mode to continue.");
      return;
    }
    if (!dateOfBirth) {
      setError("Enter your date of birth to continue.");
      return;
    }
    if (!sex) {
      setError("Select your sex to continue.");
      return;
    }
    if (!location.trim()) {
      setError("Enter your location to continue.");
      return;
    }
    if (!phone.trim()) {
      setError("Enter a phone number (WhatsApp preferred) to continue.");
      return;
    }
    setError("");
    setLoading(true);
    try {
      const result = await createBookingDraft({
        type,
        mode,
        dateOfBirth,
        sex,
        location,
        phone,
      });
      setBooking(result);
      // Prepopulate the amount with the expected fee for the chosen
      // consultation type — the patient can still correct it in step 2 if
      // they actually sent a different amount.
      setAmountPaid(String(CONSULTATION_FEES[type]));
      setStep(1);
    } catch (e) {
      setError("Something went wrong creating your booking. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  async function handleSubmitProof(e) {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      await submitPaymentProof({
        bookingId: booking.bookingId,
        momoName,
        momoReference: booking.referenceCode,
        momoTransactionId,
        amountPaid,
      });
      setStep(3);
    } catch (e) {
      setError(
        e.message ||
          "Could not submit your payment details. Please check and try again.",
      );
    } finally {
      setLoading(false);
    }
  }

  function resetFlow() {
    setStep(0);
    setType("OPD");
    setMode("online");
    setDateOfBirth("");
    setSex("");
    setLocation("");
    setPhone("");
    setBooking(null);
    setMomoName("");
    setMomoTransactionId("");
    setAmountPaid("");
    setError("");
  }

  return (
    <div className="font-body text-[#142138] bg-white min-h-screen overflow-x-hidden flex flex-col">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&family=Inter:wght@400;500;600;700&display=swap');
        :root { --brand-orange:#F88535; --ink:#142138; --teal:#1F7A6C; --tint:#FFF4EA; }
        .font-display { font-family: 'Fraunces', serif; }
        .font-body { font-family: 'Inter', sans-serif; }
        @keyframes stepIn {
          from { opacity: 0; transform: translateY(8px); }
          to { opacity: 1; transform: translateY(0); }
        }
      `}</style>

      <Header
        variant="minimal"
        cancelHref="/"
        cancelLabel="Cancel"
        isLoggedIn={isLoggedIn}
      />

      <main className="mx-auto max-w-3xl px-5 sm:px-8 py-10 sm:py-14 flex-1 w-full">
        {/* ---------- Step indicator ---------- */}
        <ol className="flex items-center gap-2 sm:gap-3 mb-3 sm:mb-12">
          {STEP_LABELS.map((label, i) => (
            <li key={label} className="flex items-center flex-1 last:flex-none">
              <div className="flex items-center gap-2 sm:gap-2.5">
                <span
                  className={
                    "flex items-center justify-center h-7 w-7 sm:h-8 sm:w-8 rounded-full text-[14px] font-medium shrink-0 " +
                    (i < step
                      ? "bg-[var(--teal)] text-white"
                      : i === step
                        ? "bg-[var(--brand-orange)] text-white"
                        : "bg-[#1421381f] text-[#142138b8]")
                  }
                >
                  {i < step ? (
                    <svg width="13" height="13" viewBox="0 0 20 20" fill="none">
                      <path
                        d="M4 10l4 4l8-8"
                        stroke="white"
                        strokeWidth="2.4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  ) : (
                    i + 1
                  )}
                </span>
                <span
                  className={
                    "hidden sm:inline text-[14px] " +
                    (i === step
                      ? "text-[var(--ink)] font-medium"
                      : "text-[#142138b8]")
                  }
                >
                  {label}
                </span>
              </div>
              {i < STEP_LABELS.length - 1 && (
                <span className="flex-1 h-px bg-[#14213822] mx-2 sm:mx-3" />
              )}
            </li>
          ))}
        </ol>
        {/* Mobile equivalent of the desktop step labels, which are hidden
            below sm to keep the dots from crowding a narrow screen. */}
        <p className="sm:hidden mb-9 text-[14px] text-[#142138b8]">
          Step {step + 1} of {STEP_LABELS.length} — {STEP_LABELS[step]}
        </p>

        {error && (
          <div className="mb-6 rounded-xl bg-[#c0392b0d] border border-[#c0392b33] text-[#c0392b] text-[15px] px-4 py-3">
            {error}
          </div>
        )}

        <div
          key={step}
          className="motion-safe:[animation:stepIn_0.35s_ease-out_both]"
        >
          {/* ---------- Step 0: consultation details ---------- */}
          {step === 0 && (
            <section>
              <h1 className="font-display text-[26px] sm:text-[30px] font-medium">
                What kind of consultation do you need?
              </h1>
              <p className="mt-2 text-[16px] text-[#142138e6]">
                You'll be able to choose a doctor and time after payment is
                confirmed.
              </p>

              <fieldset className="mt-8">
                <legend className="text-[15px] font-medium mb-3">
                  Consultation type
                </legend>
                <div className="grid sm:grid-cols-2 gap-3">
                  {[
                    {
                      key: "OPD",
                      title: "General OPD",
                      desc: "Everyday health concerns and check-ups.",
                    },
                    {
                      key: "SURGICAL",
                      title: "Surgical",
                      desc: "Pre- or post-surgery consultations.",
                    },
                  ].map((opt) => (
                    <button
                      key={opt.key}
                      type="button"
                      onClick={() => setType(opt.key)}
                      aria-pressed={type === opt.key}
                      className={
                        "text-left rounded-2xl p-5 border-2 transition-colors " +
                        (type === opt.key
                          ? "border-[var(--brand-orange)] bg-[var(--tint)]"
                          : "border-[#14213822] hover:border-[#14213855]")
                      }
                    >
                      <span className="block font-medium text-[16px]">
                        {opt.title}
                      </span>
                      <span className="block mt-1 text-[14px] text-[#142138e6]">
                        {opt.desc}
                      </span>
                      <span className="block mt-3 text-[14px] font-medium text-[var(--brand-orange)]">
                        GHS {CONSULTATION_FEES[opt.key]}
                      </span>
                    </button>
                  ))}
                </div>
              </fieldset>

              <fieldset className="mt-8">
                <legend className="text-[15px] font-medium mb-3">Mode</legend>
                <div className="grid sm:grid-cols-2 gap-3">
                  {[
                    {
                      key: "online",
                      title: "Online",
                      desc: "Video consultation from your phone or computer.",
                    },
                    {
                      key: "offline",
                      title: "In person",
                      desc: "Visit the hospital for your appointment.",
                    },
                  ].map((opt) => (
                    <button
                      key={opt.key}
                      type="button"
                      onClick={() => setMode(opt.key)}
                      aria-pressed={mode === opt.key}
                      className={
                        "text-left rounded-2xl p-5 border-2 transition-colors " +
                        (mode === opt.key
                          ? "border-[var(--brand-orange)] bg-[var(--tint)]"
                          : "border-[#14213822] hover:border-[#14213855]")
                      }
                    >
                      <span className="block font-medium text-[16px]">
                        {opt.title}
                      </span>
                      <span className="block mt-1 text-[14px] text-[#142138e6]">
                        {opt.desc}
                      </span>
                    </button>
                  ))}
                </div>
              </fieldset>

              <fieldset className="mt-8">
                <legend className="text-[15px] font-medium mb-3">
                  Your details
                </legend>
                <div className="grid sm:grid-cols-2 gap-4">
                  <div>
                    <label
                      htmlFor="dateOfBirth"
                      className="block text-[15px] font-medium mb-1.5"
                    >
                      Date of birth
                    </label>
                    <input
                      id="dateOfBirth"
                      type="date"
                      required
                      value={dateOfBirth}
                      onChange={(e) => setDateOfBirth(e.target.value)}
                      className="w-full rounded-xl border border-[#14213833] px-4 py-3 text-[16px]
                                 focus:outline-none focus:border-[var(--brand-orange)] focus:ring-1 focus:ring-[var(--brand-orange)]"
                    />
                  </div>

                  <div>
                    <label
                      htmlFor="sex"
                      className="block text-[15px] font-medium mb-1.5"
                    >
                      Sex
                    </label>
                    <select
                      id="sex"
                      required
                      value={sex}
                      onChange={(e) => setSex(e.target.value)}
                      className="w-full rounded-xl border border-[#14213833] bg-white px-4 py-3 text-[16px]
                                 focus:outline-none focus:border-[var(--brand-orange)] focus:ring-1 focus:ring-[var(--brand-orange)]"
                    >
                      <option value="" disabled>
                        Select sex
                      </option>
                      <option value="female">Female</option>
                      <option value="male">Male</option>
                    </select>
                  </div>

                  <div>
                    <label
                      htmlFor="location"
                      className="block text-[15px] font-medium mb-1.5"
                    >
                      Location
                    </label>
                    <input
                      id="location"
                      type="text"
                      required
                      value={location}
                      onChange={(e) => setLocation(e.target.value)}
                      placeholder="e.g. Berekum, Kato"
                      className="w-full rounded-xl border border-[#14213833] px-4 py-3 text-[16px]
                                 focus:outline-none focus:border-[var(--brand-orange)] focus:ring-1 focus:ring-[var(--brand-orange)]"
                    />
                  </div>

                  <div>
                    <label
                      htmlFor="phone"
                      className="block text-[15px] font-medium mb-1.5"
                    >
                      Phone number (WhatsApp preferred)
                    </label>
                    <input
                      id="phone"
                      type="tel"
                      required
                      value={phone}
                      onChange={(e) => setPhone(e.target.value)}
                      placeholder="e.g. 024 000 0000"
                      className="w-full rounded-xl border border-[#14213833] px-4 py-3 text-[16px]
                                 focus:outline-none focus:border-[var(--brand-orange)] focus:ring-1 focus:ring-[var(--brand-orange)]"
                    />
                  </div>
                </div>
              </fieldset>

              <button
                type="button"
                onClick={handleContinueFromDetails}
                disabled={loading}
                className="mt-10 w-full sm:w-auto rounded-full bg-[var(--brand-orange)] text-white text-[16px] font-medium px-7 py-3.5
                           hover:brightness-95 active:brightness-90 transition disabled:opacity-60"
              >
                {loading ? "Setting up your booking…" : "Continue to payment"}
              </button>
            </section>
          )}

          {/* ---------- Step 1: payment instructions ---------- */}
          {step === 1 && booking && (
            <section>
              <BackButton onClick={() => goToStep(0)}>
                Back to consultation details
              </BackButton>

              <h1 className="font-display text-[26px] sm:text-[30px] font-medium">
                Pay by mobile money
              </h1>
              <p className="mt-2 text-[16px] text-[#142138e6]">
                Please transfer the fee below using the reference code provided
                below as the payment reference. After completing the
                transaction, copy the transaction ID from the transaction
                message you receive and get back here.
              </p>

              <div className="mt-7 rounded-2xl border border-[#14213822] p-6 sm:p-7 space-y-5">
                <div className="flex items-center justify-between gap-4">
                  <span className="text-[15px] text-[#142138e6]">
                    Amount to pay
                  </span>
                  <span className="font-display text-[20px] font-medium">
                    GHS {fee}
                  </span>
                </div>
                <div className="flex items-center justify-between gap-4 border-t border-[#14213814] pt-5">
                  <span className="text-[15px] text-[#142138e6]">Send to</span>
                  <span className="text-right">
                    <span className="block font-medium text-[16px]">
                      {MOMO_NUMBER}
                    </span>
                    <span className="block text-[14px] text-[#142138b8]">
                      {MOMO_NAME}
                    </span>
                  </span>
                </div>
                <div className="flex items-center justify-between gap-3 border-t border-[#14213814] pt-5">
                  <span className="text-[15px] text-[#142138e6] shrink-0">
                    Reference code
                  </span>
                  <span className="flex items-center gap-2 min-w-0">
                    <span className="font-display text-[16px] sm:text-[19px] font-medium tracking-normal sm:tracking-wide text-[var(--brand-orange)] whitespace-nowrap">
                      {booking.referenceCode}
                    </span>
                    <CopyButton value={booking.referenceCode} />
                  </span>
                </div>
              </div>

              <p className="mt-5 text-[14px] bg-[#16211B] px-4 py-2 rounded text-yellow-500 leading-relaxed">
                Important: use{" "}
                <span className="font-medium text-white">
                  {booking.referenceCode}
                </span>{" "}
                as the transfer reference, so our team can confirm your payment.
              </p>

              <button
                type="button"
                onClick={() => goToStep(2)}
                className="mt-8 w-full sm:w-auto rounded-full bg-[var(--brand-orange)] text-white text-[16px] font-medium px-7 py-3.5
                           hover:brightness-95 active:brightness-90 transition"
              >
                I've made the payment
              </button>
            </section>
          )}

          {/* ---------- Step 2: submit payment proof ---------- */}
          {step === 2 && booking && (
            <section>
              <BackButton onClick={() => goToStep(1)}>
                Back to payment instructions
              </BackButton>

              <h1 className="font-display text-[26px] sm:text-[30px] font-medium">
                Confirm your payment
              </h1>
              <p className="mt-2 text-[16px] text-[#142138e6]">
                Tell us the details from your mobile money transfer so our team
                can verify it.
              </p>

              <form
                onSubmit={handleSubmitProof}
                className="mt-7 space-y-5 max-w-md"
              >
                <div>
                  <span className="block text-[15px] font-medium mb-1.5">
                    Transaction reference
                  </span>
                  <div className="flex items-center gap-2.5 rounded-xl border border-[#14213822] bg-[#14213808] px-4 py-3">
                    <span className="flex-1 min-w-0 text-[16px] font-medium tracking-normal sm:tracking-wide whitespace-nowrap overflow-x-auto">
                      {booking.referenceCode}
                    </span>
                    <CopyButton value={booking.referenceCode} />
                  </div>
                  <p className="mt-1.5 text-[13px] text-[#142138b8]">
                    This is the code you used as your transfer note, it's fixed
                    to this booking.
                  </p>
                </div>

                <div>
                  <label
                    htmlFor="momoTransactionId"
                    className="block text-[15px] font-medium mb-1.5"
                  >
                    Mobile money transaction ID
                  </label>
                  <input
                    id="momoTransactionId"
                    type="text"
                    required
                    value={momoTransactionId}
                    onChange={(e) => setMomoTransactionId(e.target.value)}
                    className="w-full rounded-xl border border-[#14213833] px-4 py-3 text-[16px]
                               focus:outline-none focus:border-[var(--brand-orange)] focus:ring-1 focus:ring-[var(--brand-orange)]"
                    placeholder="e.g. CI250915.1234.A56789"
                  />
                  <p className="mt-1.5 text-[13px] text-[#142138b8] leading-relaxed">
                    Check the SMS you received after sending the money, it
                    contains a Transaction ID. Copy that ID and paste it here.
                  </p>
                </div>

                <div>
                  <label
                    htmlFor="momoName"
                    className="block text-[15px] font-medium mb-1.5"
                  >
                    Name on the MoMo account used
                  </label>
                  <input
                    id="momoName"
                    type="text"
                    required
                    value={momoName}
                    onChange={(e) => setMomoName(e.target.value)}
                    className="w-full rounded-xl border border-[#14213833] px-4 py-3 text-[16px]
                               focus:outline-none focus:border-[var(--brand-orange)] focus:ring-1 focus:ring-[var(--brand-orange)]"
                    placeholder="e.g. Ama Serwaa"
                  />
                </div>

                <div>
                  <label
                    htmlFor="amountPaid"
                    className="block text-[15px] font-medium mb-1.5"
                  >
                    Amount sent (GHS)
                  </label>
                  <input
                    id="amountPaid"
                    type="number"
                    min="0"
                    step="0.01"
                    required
                    value={amountPaid}
                    onChange={(e) => setAmountPaid(e.target.value)}
                    className="w-full rounded-xl border border-[#14213833] px-4 py-3 text-[16px]
                               focus:outline-none focus:border-[var(--brand-orange)] focus:ring-1 focus:ring-[var(--brand-orange)]"
                  />
                  <p className="mt-1.5 text-[13px] text-[#142138b8]">
                    Pre-filled with the expected fee, change it only if you
                    actually sent a different amount.
                  </p>
                </div>

                <button
                  type="submit"
                  disabled={loading}
                  className="w-full sm:w-auto rounded-full bg-[var(--brand-orange)] text-white text-[16px] font-medium px-7 py-3.5
                             hover:brightness-95 active:brightness-90 transition disabled:opacity-60"
                >
                  {loading ? "Submitting…" : "Submit payment details"}
                </button>
              </form>
            </section>
          )}

          {/* ---------- Step 3: confirmation / pending ---------- */}
          {step === 3 && booking && (
            <section className="text-center sm:text-left">
              <div className="mx-auto sm:mx-0 h-14 w-14 rounded-full bg-[var(--tint)] flex items-center justify-center">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                  <path
                    d="M5 13l4 4l10-10"
                    stroke="var(--teal)"
                    strokeWidth="2.4"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
              </div>
              <h1 className="mt-5 font-display text-[26px] sm:text-[30px] font-medium">
                Your booking is being reviewed
              </h1>
              <p className="mt-2 text-[16px] text-[#142138e6] max-w-md mx-auto sm:mx-0">
                Our team is verifying your payment. Once confirmed, we'll call
                or WhatsApp you with your appointment time and consultation ID.
              </p>

              <div className="mt-7 inline-flex items-center gap-3 rounded-2xl border border-[#14213822] px-6 py-4 text-left max-w-full">
                <span className="min-w-0">
                  <span className="block text-[14px] text-[#142138b8]">
                    Your reference code
                  </span>
                  <span className="block font-display text-[17px] sm:text-[21px] font-medium tracking-normal sm:tracking-wide text-[var(--brand-orange)] whitespace-nowrap overflow-x-auto">
                    {booking.referenceCode}
                  </span>
                </span>
                <CopyButton value={booking.referenceCode} />
              </div>

              <p className="mt-6 text-[14px] text-[#142138b8]">
                Keep this code, you'll need it together with your account to
                request a reschedule later.
              </p>

              <div className="mt-8 flex flex-wrap justify-center sm:justify-start gap-3">
                <Link
                  to="/"
                  className="rounded-full border border-[#14213833] text-[16px] font-medium px-6 py-3
                             hover:border-[var(--ink)] transition"
                >
                  Back to home
                </Link>
                <button
                  type="button"
                  onClick={resetFlow}
                  className="rounded-full bg-[var(--brand-orange)] text-white text-[16px] font-medium px-6 py-3
                             hover:brightness-95 active:brightness-90 transition"
                >
                  Book another consultation
                </button>
              </div>
            </section>
          )}
        </div>
      </main>

      <Footer />
    </div>
  );
}
