import { useState } from "react";
import { IconCheck, IconX, IconAlert } from "./icons.jsx";

// 4.4 — the Activity tab surfaces reference-ledger events with the account
// involved and the exact server timestamp, so staff can see if someone is
// trying to reuse a code.
const META = {
  confirmed: {
    icon: IconCheck,
    bg: "var(--color-success-bg)",
    fg: "var(--color-success)",
    label: "Confirmed",
    text: (a) => `${a.account} confirmed payment for ${a.referenceCode}`,
  },
  rejected: {
    icon: IconX,
    bg: "var(--color-danger-bg)",
    fg: "var(--color-danger)",
    label: "Rejected",
    text: (a) =>
      `${a.account} rejected reference ${a.referenceCode} — code released back to available`,
  },
  blocked_duplicate: {
    icon: IconAlert,
    bg: "var(--color-warning-bg)",
    fg: "var(--color-warning)",
    label: "Blocked reuse",
    text: (a) =>
      `Reuse of ${a.referenceCode} was refused at submission — attempted by ${a.account}`,
  },
  mismatch: {
    icon: IconAlert,
    bg: "var(--color-danger-bg)",
    fg: "var(--color-danger)",
    label: "Mismatch",
    text: (a) =>
      `${a.account} entered MoMo details for ${a.referenceCode} that did not match the patient's submission`,
  },
};

const FILTERS = [
  { key: "all", label: "All events" },
  { key: "blocked_duplicate", label: "Blocked reuse" },
  { key: "confirmed", label: "Confirmations" },
  { key: "rejected", label: "Rejections" },
  { key: "mismatch", label: "Mismatches" },
];

export default function ActivityPanel({ events }) {
  const [filter, setFilter] = useState("all");

  const rows =
    filter === "all" ? events : events.filter((e) => e.type === filter);

  const blocked = events.filter(
    (e) => e.type === "blocked_duplicate",
  ).length;

  return (
    <>
      {blocked > 0 && (
        <div className="admin-banner warn">
          <IconAlert size={18} />
          <p>
            {blocked} reuse {blocked === 1 ? "attempt was" : "attempts were"}{" "}
            blocked recently. Each was refused before a booking could be
            created. Repeated attempts from one account are worth reviewing in
            the audit log.
          </p>
        </div>
      )}

      <section className="admin-panel">
        <div className="admin-panel-head">
          <div>
            <h2>Reference-ledger activity</h2>
            <p>
              Timestamps are generated by the server, never by the patient's
              device
            </p>
          </div>
        </div>

        <div className="admin-subtabs">
          {FILTERS.map((f) => (
            <button
              key={f.key}
              className={`admin-subtab${filter === f.key ? " active" : ""}`}
              onClick={() => setFilter(f.key)}
            >
              {f.label}
            </button>
          ))}
        </div>

        {rows.length === 0 ? (
          <div className="admin-empty">
            No events of this kind have been recorded.
          </div>
        ) : (
          <div className="activity-list">
            {rows.map((a) => {
              const m = META[a.type];
              const Icon = m.icon;
              return (
                <div className="activity-row" key={a.id}>
                  <div
                    className="activity-icon"
                    style={{ background: m.bg, color: m.fg }}
                  >
                    <Icon size={14} />
                  </div>
                  <div>
                    <div className="activity-text">{m.text(a)}</div>
                    <div className="activity-meta">
                      {new Date(a.timestamp).toLocaleString()}
                    </div>
                  </div>
                  <span className={`status-pill ${a.type}`}>{m.label}</span>
                </div>
              );
            })}
          </div>
        )}
      </section>
    </>
  );
}
